backend:
  name: github
  repo: shawn-ycx/lareinart

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Post
    folder: post
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    card: {type: "image", image: "image", text: "title"}